SELECT DISTINCT CEDENTE_NOMBRE, 
CESIONARIO_NOMBRE, 
SIPPERS47_CANT_CUOTAS,
SP01_MOTIVO1.SIPPERS01_VALOR
               MOTIVO_1,
           SP01_MOTIVO2.SIPPERS01_VALOR
               MOTIVO_2,
           SP01_MOTIVO3.SIPPERS01_VALOR
               MOTIVO_3, 
               SIP_PERS_47.SIPPERS47_OBSERVACION,
           SIP_PERS_47.ID_SIPPERS47,
           SIP_PERS_47.SIPPERS47_FBAJA,
           SIP_PERS_47.RELA_SIPPERS45_CEDENTE
               RELA_SIPPERS45_CEDENTE,
           SIP_PERS_47.RELA_SIPPERS45_CESIONARIO
               RELA_SIPPERS45_CESIONARIO,
           SIP_PERS_47.RELA_SIPPERS06
               RELA_SIPPERS06,
           SIP_PERS_47.SIPPERS47_FECHA
               SIPPERS47_FECHA,
           SP45_CEDENTE.RELA_SIPPERS15
               CEDENTE_RELA_SIPPERS05,
           SP45_CESIONARIOS.RELA_SIPPERS15
               CESIONARIO_RELA_SIPPERS05,
           SP45_CESIONARIOS.RELA_SOCUSUA01_ALTA
               RELA_SOCUSUA01_ALTA
      FROM SIP_PERS_47
           JOIN SIP_PERS_45 SP45_CEDENTE
              ON SP45_CEDENTE.ID_SIPPERS45 =
                 SIP_PERS_47.RELA_SIPPERS45_CEDENTE
           JOIN (
               SELECT SP06_CEDENTE.SIPPERS06_RAZSOC CEDENTE_NOMBRE,SP06_CEDENTE.RELA_SIPPERS15 AS RELA_SIPPERS15_SUB
               FROM SIP_PERS_45 SP45_CEDENTE
               JOIN SIP_PERS_06 SP06_CEDENTE
               ON SP06_CEDENTE.RELA_SIPPERS15 = SP45_CEDENTE.RELA_SIPPERS15
               
               UNION ALL
             
               SELECT SP05_CEDENTE.SIPPERS05_APELLIDO
               || ' '
               || SP05_CEDENTE.SIPPERS05_NOMBRE CEDENTE_NOMBRE,SP05_CEDENTE.RELA_SIPPERS15 AS RELA_SIPPERS15_SUB
               FROM SIP_PERS_45 SP45_CEDENTE
               JOIN SIP_PERS_05 SP05_CEDENTE
               ON SP05_CEDENTE.RELA_SIPPERS15 = SP45_CEDENTE.RELA_SIPPERS15
               ) CONSULTA_CEDENTES
              ON CONSULTA_CEDENTES.RELA_SIPPERS15_SUB = SP45_CEDENTE.RELA_SIPPERS15
           
            JOIN SIP_PERS_45 SP45_CESIONARIOS
              ON SP45_CESIONARIOS.ID_SIPPERS45 =
                 SIP_PERS_47.RELA_SIPPERS45_CESIONARIO
                 
           JOIN ( 
               SELECT SP06_CESIONARIO.SIPPERS06_RAZSOC CESIONARIO_NOMBRE,SP06_CESIONARIO.RELA_SIPPERS15 AS RELA_SIPPERS15_SUB
               FROM SIP_PERS_45 SP45_CESIONARIO
               JOIN SIP_PERS_06 SP06_CESIONARIO
               ON SP06_CESIONARIO.RELA_SIPPERS15 = SP45_CESIONARIO.RELA_SIPPERS15
               
               UNION ALL
             
               SELECT SP05_CESIONARIO.SIPPERS05_APELLIDO
               || ' '
               || SP05_CESIONARIO.SIPPERS05_NOMBRE CESIONARIO_NOMBRE,SP05_CESIONARIO.RELA_SIPPERS15 AS RELA_SIPPERS15_SUB
               FROM SIP_PERS_45 SP45_CESIONARIO
               JOIN SIP_PERS_05 SP05_CESIONARIO
               ON SP05_CESIONARIO.RELA_SIPPERS15 = SP45_CESIONARIO.RELA_SIPPERS15
               ) CONSULTA_CESIONARIOS
              ON CONSULTA_CESIONARIOS.RELA_SIPPERS15_SUB = SP45_CESIONARIOS.RELA_SIPPERS15
           
           LEFT JOIN
           (SELECT *
              FROM SIP_PERS_51
                   JOIN SIP_PERS_01
                       ON ID_SIPPERS01 = SIP_PERS_51.RELA_SIPPERS01
             WHERE SIPPERS01_CODE = 'CES03' OR SIPPERS01_CODE = 'CES04')
           SP01_MOTIVO1
               ON SP01_MOTIVO1.RELA_SIPPERS47 = SIP_PERS_47.ID_SIPPERS47
           --
           LEFT JOIN
           (SELECT *
              FROM SIP_PERS_51
                   JOIN SIP_PERS_01
                       ON ID_SIPPERS01 = SIP_PERS_51.RELA_SIPPERS01
             WHERE SIPPERS01_CODE = 'CES05' OR SIPPERS01_CODE = 'CES06')
           SP01_MOTIVO2
               ON SP01_MOTIVO2.RELA_SIPPERS47 = SIP_PERS_47.ID_SIPPERS47
 
           LEFT JOIN
           (SELECT *
              FROM SIP_PERS_51
                   JOIN SIP_PERS_01
                       ON ID_SIPPERS01 = SIP_PERS_51.RELA_SIPPERS01
             WHERE    SIPPERS01_CODE = 'CES07'
                   OR SIPPERS01_CODE = 'CES08'
                   OR SIPPERS01_CODE = 'CES09') SP01_MOTIVO3
               ON SP01_MOTIVO3.RELA_SIPPERS47 = SIP_PERS_47.ID_SIPPERS47

WHERE SIP_PERS_47.RELA_SIPPERS06=505052 and SIPPERS47_FBAJA IS null;