// Generated by https://quicktype.io

import { Evento } from "./Evento";

export interface AntecedenteMedicoFamiliar {
    id: number;
    rela_tipo: number;
    rela_evento: number;
    rela_paciente: number;
    evento: Evento;
}


